const email = `azpsm9@gmail.com
6ambruby@gmail.com
6ambtopaz@gmail.com
zhannacherkasova92@gmail.com
shevchenkokatya40@gmail.com
oluakuzmenko@gmail.com
switlana.trofimuk@gmail.com
nvb10103@gmail.com
nr_cpmsd@ukr.net
super.opti@ukr.net
elenaisaeva1960@gmail.com
rudaua12345@gmail.com
tivtsa@gmail.com
shenkarenko.olga@ukr.net
solone.centr@gmail.com
bogcpmsd@ukr.net
negoda1082@gmail.com
lidiya12ua@gmail.com
chudovanatalia25@gmail.com
chornovol2008@ukr.net
chornovol2008@ukr.net
svetlana_stanislavovna@ukr.net
nadia.cuznetsova2018@gmail.com
victoriakoshlabo@gmail.com
ppmsd@ukr.net
yelena.stavr.med@gmail.com
babiyvvdazpsm@ukr.net
rita-tiki-tavi@ukr.net
llkovyazina@gmail.com
lenaaa1970@gmail.com
shcherbatays_likar@ukr.net
shcherbatays_likar@ukr.net
tutunnikalesya@gmai.com
maria232633@gmail.com
dcpmsd10.ambulance1@gmail.com
svetlanafilyanovich@gmail.com
vkocuba2805@gmail.com
l7.nimik.pavl@gmail.com
yurchenko-lyubov@ukr.net
yucpmsd2017@gmail.com
MereshkoNata@gmail.com
rusinko1948@gmail.com
dr.rudenc@gmail.com
lotysh.olga1609@gmail.com
koliadenko.len@gmail.com
ka.merzlyak@gmail.com
larisakorota@gmail.com
borisenko_75@i.ua
shvecnelli@gmail.com
annasolodun@gmail.com
alena.grois@ukr.net
im.olgaboyko@gmail.com
olegovnaevgenia27@gmail.com
annanicyk3@gmail.com
omarkina41@gmail.com
t10061957@gmail.com
edikhandyukdp@gmail.com
novoselivskasla@i.ua
tarabrinata@i.ua
katsilo62@gmail.com
pedan.avicena@gmail.com
cemerisulia6@gmail.com
korpusenko.leonid@gmail.com
ivolga3791@gmail.com
solomkaanna95@gmail.com
iravlsk@gmail.com
irin_shepel@ukr.net
kobuchno@i.ua
kkiti@ukr.net
larisakorota@gmail.com
likar304-2@ukr.net
lina.colovska@gmail.com
oksana_vladimirovna7@ukr.net
nataamb2@gmail.com
tkachova.s70@gmail.com
injir.jir997@gmail.com
aleksandrenkodaryna9.1@gmail.com
yulia_vasilievna@ukr.net
levinvalerij68@gmail.com
5106berlova@gmail.com
oksanabugir27@gmail.com
tatianasvitlyk1981@gmail.com
irinazavadskaya70@gmail.com
vipogan@mail.ru
aleksandrbalagov88@gmail.com
kovgen@ukr.net
chuckoo125@gmail.com
dilnycya43@i.ua
inna.zelena.doc@gmail.com
makovceva1952@gmail.com
klymetsyuliia280198@gmail.com
nastik16021996@gmail.com
mega.ambulance9@ukr.net
iraira19582020@gmail.com
lisovolvaceslav@gmail.com
bezverhovaolga0508
anna.kondratenko04@gimeil.com
elenakinash777@gmail.com
samsonova2021@gmail.com
sevasch150@gmail.com
manuylovainna@ukr.ner
vladislavshmuryhin@gmail.com
inna.sharamor@gmail.com
dr.kosolapovaia@gmail.com
yur.yurchenko@ukr.net
tatianasvitlyk@gmail.com
denisenkoalla20190gmail.com
dcpmsd.4@gmail.com
katyavoznuik@gmail.com
ponomarenko_nat@ukr.net
mariako4ederia@gmail.com
elizavetabatracenko@gmail.com
dienycya43@i.ua
sincpmsb@ukr.net
opediat21@gmail.com
irinavishina1967@gmail.com
tinaholoviankogu@gmail.com
samsonova2021a@gmail.com
funn45@gmail.com`;

const all = `azpsm9@gmail.com
6ambruby@gmail.com
6ambtopaz@gmail.com
zhannacherkasova92@gmail.com
shevchenkokatya40@gmail.com
oluakuzmenko@gmail.com
switlana.trofimuk@gmail.com
nvb10103@gmail.com
nr_cpmsd@ukr.net
super.opti@ukr.net
elenaisaeva1960@gmail.com
rudaua12345@gmail.com
tivtsa@gmail.com
shenkarenko.olga@ukr.net
solone.centr@gmail.com
bogcpmsd@ukr.net
negoda1082@gmail.com
lidiya12ua@gmail.com
chudovanatalia25@gmail.com
chornovol2008@ukr.net
chornovol2008@ukr.net
svetlana_stanislavovna@ukr.net
nadia.cuznetsova2018@gmail.com
victoriakoshlabo@gmail.com
ppmsd@ukr.net
yelena.stavr.med@gmail.com
babiyvvdazpsm@ukr.net
rita-tiki-tavi@ukr.net
llkovyazina@gmail.com
lenaaa1970@gmail.com
shcherbatays_likar@ukr.net
shcherbatays_likar@ukr.net
tutunnikalesya@gmai.com
maria232633@gmail.com
dcpmsd10.ambulance1@gmail.com
svetlanafilyanovich@gmail.com
vkocuba2805@gmail.com
l7.nimik.pavl@gmail.com
yurchenko-lyubov@ukr.net
yucpmsd2017@gmail.com
MereshkoNata@gmail.com
rusinko1948@gmail.com
dr.rudenc@gmail.com
lotysh.olga1609@gmail.com
koliadenko.len@gmail.com
ka.merzlyak@gmail.com
larisakorota@gmail.com
borisenko_75@i.ua
shvecnelli@gmail.com
annasolodun@gmail.com
alena.grois@ukr.net
im.olgaboyko@gmail.com
olegovnaevgenia27@gmail.com
annanicyk3@gmail.com
omarkina41@gmail.com
t10061957@gmail.com
edikhandyukdp@gmail.com
novoselivskasla@i.ua
tarabrinata@i.ua
katsilo62@gmail.com
pedan.avicena@gmail.com
cemerisulia6@gmail.com
korpusenko.leonid@gmail.com
ivolga3791@gmail.com
solomkaanna95@gmail.com
iravlsk@gmail.com
irin_shepel@ukr.net
kobuchno@i.ua
kkiti@ukr.net
larisakorota@gmail.com
likar304-2@ukr.net
lina.colovska@gmail.com
oksana_vladimirovna7@ukr.net
nataamb2@gmail.com
tkachova.s70@gmail.com
injir.jir997@gmail.com
aleksandrenkodaryna9.1@gmail.com
yulia_vasilievna@ukr.net
levinvalerij68@gmail.com
5106berlova@gmail.com
oksanabugir27@gmail.com
tatianasvitlyk1981@gmail.com
irinazavadskaya70@gmail.com
vipogan@mail.ru
aleksandrbalagov88@gmail.com
kovgen@ukr.net
chuckoo125@gmail.com
dilnycya43@i.ua
inna.zelena.doc@gmail.com
makovceva1952@gmail.com
klymetsyuliia280198@gmail.com
nastik16021996@gmail.com
mega.ambulance9@ukr.net
iraira19582020@gmail.com
lisovolvaceslav@gmail.com
bezverhovaolga0508
anna.kondratenko04@gimeil.com
elenakinash777@gmail.com
samsonova2021@gmail.com
sevasch150@gmail.com
manuylovainna@ukr.ner
vladislavshmuryhin@gmail.com
inna.sharamor@gmail.com
dr.kosolapovaia@gmail.com
yur.yurchenko@ukr.net
tatianasvitlyk@gmail.com
denisenkoalla20190gmail.com
dcpmsd.4@gmail.com
katyavoznuik@gmail.com
ponomarenko_nat@ukr.net
mariako4ederia@gmail.com
elizavetabatracenko@gmail.com
dienycya43@i.ua
sincpmsb@ukr.net
opediat21@gmail.com
irinavishina1967@gmail.com
tinaholoviankogu@gmail.com
samsonova2021a@gmail.com
funn45@gmail.com`;

const odd = `oksanabugir27@gmail.com
katyavoznuik@gmail.com
oluakuzmenko@gmail.com
alena.grois@ukr.net
koliadenko.len@gmail.com
dr.kosolapovaia@gmail.com
annanicyk3@gmail.com
maria232633@gmail.com
ponomarenko_nat@ukr.net
lidiya12ua@gmail.com
rudaua12345@gmail.com
solomkaanna95@gmail.com
edikhandyukdp@gmail.com
shenkarenko.olga@ukr.net
irin_shepel@ukr.net
rita-tiki-tavi@ukr.net
mariako4ederia@gmail.com
im.olgaboyko@gmail.com
pedan.avicena@gmail.com
elenaisaeva1960@gmail.com
dcpmsd10.ambulance1@gmail.com
yurchenko-lyubov@ukr.net
omarkina41@gmail.com
irinazavadskaya70@gmail.com
bogcpmsd@ukr.net
shvecnelli@gmail.com
cemerisulia6@gmail.com
aleksandrenkodaryna9.1@gmail.com
yelena.stavr.med@gmail.com
vladislavshmuryhin@gmail.com
lina.colovska@gmail.com
oksana_vladimirovna7@ukr.net
levinvalerij68@gmail.com
svetlanafilyanovich@gmail.com
dr.rudenc@gmail.com
svetlana_stanislavovna@ukr.net
lotysh.olga1609@gmail.com
kobuchno@i.ua
korpusenko.leonid@gmail.com
larisakorota@gmail.com
klymetsyuliia280198@gmail.com
llkovyazina@gmail.com
nataamb2@gmail.com
dcpmsd.4@gmail.com
aleksandrbalagov88@gmail.com
tkachova.s70@gmail.com
nastik16021996@gmail.com
makovceva1952@gmail.com
likar304-2@ukr.net
victoriakoshlabo@gmail.com
5106berlova@gmail.com
borisenko_75@i.ua
iraira19582020@gmail.com
tivtsa@gmail.com
azpsm9@gmail.com
lenaaa1970@gmail.com
iravlsk@gmail.com
nr_cpmsd@ukr.net
lisovolvaceslav@gmail.com
chornovol2008@ukr.net
injir.jir997@gmail.com
elenakinash777@gmail.com
super.opti@ukr.net
inna.zelena.doc@gmail.com
switlana.trofimuk@gmail.com
negoda1082@gmail.com
tatianasvitlyk1981@gmail.com
nvb10103@gmail.com
mega.ambulance9@ukr.net
yucpmsd2017@gmail.com
kovgen@ukr.net
kkiti@ukr.net
elizavetabatracenko@gmail.com
zhannacherkasova92@gmail.com
chuckoo125@gmail.com
l7.nimik.pavl@gmail.com
mereshkonata@gmail.com
annasolodun@gmail.com
shcherbatays_likar@ukr.net
chudovanatalia25@gmail.com
yulia_vasilievna@ukr.net
6ambtopaz@gmail.com
ka.merzlyak@gmail.com
irinavishina1967@gmail.com
6ambruby@gmail.com
vipogan@mail.ru
dilnycya43@i.ua`;

module.exports = {
    email,
    all,
    odd,
};
